# Generated by Django 2.2.2 on 2019-08-01 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name_plural': '文章信息'},
        ),
        migrations.AlterModelOptions(
            name='articledetail',
            options={'verbose_name_plural': '文章内容'},
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name_plural': '个人博客'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': '个人文章分类'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': '评论信息'},
        ),
        migrations.AlterModelOptions(
            name='issueinfo',
            options={'verbose_name_plural': '故障单信息'},
        ),
        migrations.AlterModelOptions(
            name='updown',
            options={'verbose_name_plural': '文章点赞关系'},
        ),
        migrations.AlterUniqueTogether(
            name='updown',
            unique_together=set(),
        ),
    ]
