# Generated by Django 2.2.2 on 2019-08-06 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_auto_20190801_1626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article_type',
            new_name='article_type_id',
        ),
    ]
